[versions]
agp = "9.2.0"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
kotlin = "2.3.10"
ksp = "2.3.5"
composeBom = "2026.02.01"
roomVersion = "2.8.4"
viewModelVersion = "2.10.0"
koinVersion = "4.2.1"
coil = "3.4.0"
zxingMatrix = "3.5.3"
zxingDisplay = "4.3.0"
coroutinesTestVersion = "1.7.3"
mockkVersion = "1.13.8"
datastore = "1.2.1"
splashScreen = "1.0.1"
uiGraphics = "1.11.2"
composeIcons = "1.7.7"
desugaringVersion = "2.0.2"
navigationCompose = "2.8.8"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

#Room Database
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomVersion"}
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomVersion"}
room-coroutines = {group = "androidx.room", name = "room-ktx", version.ref = "roomVersion"}

#ViewModel
android-viewModel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "viewModelVersion"}

#Koin
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koinVersion"}
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koinVersion"}
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koinVersion"}

#Coil
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil"}

#Zing
zxing-matrix = { group = "com.google.zxing", name = "core", version.ref = "zxingMatrix"}
zxing-display = { group = "com.journeyapps", name = "zxing-android-embedded", version.ref = "zxingDisplay"}

#Test
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTestVersion" }
mockk-test = { group = "io.mockk", name = "mockk", version.ref = "mockkVersion"}

#DataStore
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

#SplashScreen
splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashScreen" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "uiGraphics" }

#JetpackCompose Icon
jetpack-compose-icon = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "composeIcons" }

#Desugaring
desugaring = { group = "com.android.tools", name = "desugar_jdk_libs_nio", version.ref = "desugaringVersion" }

#Navigation
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

