package com.victorkirui.meetnote.ui.theme
import androidx.compose.ui.graphics.Color

// Primary — Slate (App chrome, buttons, FAB, active nav)
val primaryLight = Color(0xFF45445C)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFDDD8E8)
val onPrimaryContainerLight = Color(0xFF2E2D42)

// Secondary — Midnight Blue (Work profile)
val secondaryLight = Color(0xFF0D1B4B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFC8D0E8)
val onSecondaryContainerLight = Color(0xFF0D1B4B)

// Tertiary — Terracotta (Social profile)
val tertiaryLight = Color(0xFFC4622D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFF5D5C0)
val onTertiaryContainerLight = Color(0xFF8B3A1A)

// Error — unchanged
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)

// Background & Surface
val backgroundLight = Color(0xFFFFFBFE)
val onBackgroundLight = Color(0xFF1C1B1F)
val surfaceLight = Color(0xFFFFFBFE)
val onSurfaceLight = Color(0xFF1C1B1F)
val surfaceVariantLight = Color(0xFFE5E1E9)
val onSurfaceVariantLight = Color(0xFF49454F)

// Outline
val outlineLight = Color(0xFF79747E)
val outlineVariantLight = Color(0xFFCAC4D0)

// Inverse & Scrim
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313033)
val inverseOnSurfaceLight = Color(0xFFF4EFF4)
val inversePrimaryLight = Color(0xFFCBBAFF)

// Surface containers
val surfaceDimLight = Color(0xFFDDD9DB)
val surfaceBrightLight = Color(0xFFFFFBFE)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF7F2FA)
val surfaceContainerLight = Color(0xFFF3EDF7)
val surfaceContainerHighLight = Color(0xFFECE6F0)
val surfaceContainerHighestLight = Color(0xFFE6E0E9)

val primaryLightMediumContrast = Color(0xFF2E2E45)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF45445C)
val onPrimaryContainerLightMediumContrast = Color(0xFFE0DCFA)
val secondaryLightMediumContrast = Color(0xFF36353F)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF6D6C77)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF422837)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF5A3E4E)
val onTertiaryContainerLightMediumContrast = Color(0xFFFCD5E9)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFCF8FA)
val onBackgroundLightMediumContrast = Color(0xFF1C1B1D)
val surfaceLightMediumContrast = Color(0xFFFCF8FA)
val onSurfaceLightMediumContrast = Color(0xFF111113)
val surfaceVariantLightMediumContrast = Color(0xFFE5E1E9)
val onSurfaceVariantLightMediumContrast = Color(0xFF36353C)
val outlineLightMediumContrast = Color(0xFF535258)
val outlineVariantLightMediumContrast = Color(0xFF6E6C73)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF313032)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF4F0F2)
val inversePrimaryLightMediumContrast = Color(0xFFC6C3E1)
val surfaceDimLightMediumContrast = Color(0xFFC9C5C8)
val surfaceBrightLightMediumContrast = Color(0xFFFCF8FA)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF7F2F5)
val surfaceContainerLightMediumContrast = Color(0xFFEBE7E9)
val surfaceContainerHighLightMediumContrast = Color(0xFFDFDCDE)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD4D1D3)

val primaryLightHighContrast = Color(0xFF2B2A40)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF45445C)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF2C2B35)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF494853)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF3D2433)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF5A3E4E)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFCF8FA)
val onBackgroundLightHighContrast = Color(0xFF1C1B1D)
val surfaceLightHighContrast = Color(0xFFFCF8FA)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE5E1E9)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF2C2B32)
val outlineVariantLightHighContrast = Color(0xFF49484F)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF313032)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFC6C3E1)
val surfaceDimLightHighContrast = Color(0xFFBBB8BA)
val surfaceBrightLightHighContrast = Color(0xFFFCF8FA)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF4F0F2)
val surfaceContainerLightHighContrast = Color(0xFFE5E1E4)
val surfaceContainerHighLightHighContrast = Color(0xFFD7D3D6)
val surfaceContainerHighestLightHighContrast = Color(0xFFC9C5C8)

val primaryDark = Color(0xFFC6C3E1)
val onPrimaryDark = Color(0xFF2F2E45)
val primaryContainerDark = Color(0xFF45445C)
val onPrimaryContainerDark = Color(0xFFB4B2CE)
val secondaryDark = Color(0xFFC8C5D2)
val onSecondaryDark = Color(0xFF302F39)
val secondaryContainerDark = Color(0xFF494852)
val onSecondaryContainerDark = Color(0xFFBAB7C3)
val tertiaryDark = Color(0xFFE2BCD0)
val onTertiaryDark = Color(0xFF422838)
val tertiaryContainerDark = Color(0xFF5A3E4E)
val onTertiaryContainerDark = Color(0xFFCFAABD)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF141315)
val onBackgroundDark = Color(0xFFE5E1E4)
val surfaceDark = Color(0xFF141315)
val onSurfaceDark = Color(0xFFE5E1E4)
val surfaceVariantDark = Color(0xFF47464D)
val onSurfaceVariantDark = Color(0xFFC8C5CD)
val outlineDark = Color(0xFF928F97)
val outlineVariantDark = Color(0xFF47464D)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E1E4)
val inverseOnSurfaceDark = Color(0xFF313032)
val inversePrimaryDark = Color(0xFF5D5C75)
val surfaceDimDark = Color(0xFF141315)
val surfaceBrightDark = Color(0xFF3A393B)
val surfaceContainerLowestDark = Color(0xFF0E0E10)
val surfaceContainerLowDark = Color(0xFF1C1B1D)
val surfaceContainerDark = Color(0xFF201F21)
val surfaceContainerHighDark = Color(0xFF2A2A2B)
val surfaceContainerHighestDark = Color(0xFF353436)

val primaryDarkMediumContrast = Color(0xFFDCD9F7)
val onPrimaryDarkMediumContrast = Color(0xFF24233A)
val primaryContainerDarkMediumContrast = Color(0xFF908EA9)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFDEDAE8)
val onSecondaryDarkMediumContrast = Color(0xFF25252E)
val secondaryContainerDarkMediumContrast = Color(0xFF918F9B)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFF9D1E6)
val onTertiaryDarkMediumContrast = Color(0xFF361E2D)
val tertiaryContainerDarkMediumContrast = Color(0xFFA98799)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF141315)
val onBackgroundDarkMediumContrast = Color(0xFFE5E1E4)
val surfaceDarkMediumContrast = Color(0xFF141315)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF47464D)
val onSurfaceVariantDarkMediumContrast = Color(0xFFDEDBE3)
val outlineDarkMediumContrast = Color(0xFFB3B1B9)
val outlineVariantDarkMediumContrast = Color(0xFF918F97)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE5E1E4)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2A2A2B)
val inversePrimaryDarkMediumContrast = Color(0xFF47465E)
val surfaceDimDarkMediumContrast = Color(0xFF141315)
val surfaceBrightDarkMediumContrast = Color(0xFF454446)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF070709)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1E1D1F)
val surfaceContainerDarkMediumContrast = Color(0xFF282729)
val surfaceContainerHighDarkMediumContrast = Color(0xFF333234)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3E3D3F)

val primaryDarkHighContrast = Color(0xFFF1EEFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFC2C0DD)
val onPrimaryContainerDarkHighContrast = Color(0xFF09091E)
val secondaryDarkHighContrast = Color(0xFFF2EEFC)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFC4C1CE)
val onSecondaryContainerDarkHighContrast = Color(0xFF0B0A13)
val tertiaryDarkHighContrast = Color(0xFFFFEBF3)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFDEB8CC)
val onTertiaryContainerDarkHighContrast = Color(0xFF180511)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF141315)
val onBackgroundDarkHighContrast = Color(0xFFE5E1E4)
val surfaceDarkHighContrast = Color(0xFF141315)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF47464D)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFF2EEF7)
val outlineVariantDarkHighContrast = Color(0xFFC4C1C9)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE5E1E4)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF47465E)
val surfaceDimDarkHighContrast = Color(0xFF141315)
val surfaceBrightDarkHighContrast = Color(0xFF514F52)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF201F21)
val surfaceContainerDarkHighContrast = Color(0xFF313032)
val surfaceContainerHighDarkHighContrast = Color(0xFF3C3B3D)
val surfaceContainerHighestDarkHighContrast = Color(0xFF484648)







